language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install --no-optional
  - npm install --save-dev ftp-deploy 
after_success:
  - node deploy-script.js
script: npm run build
